### ISSUE TITLE
Bug Report: App log is spamming each chat message

### ISSUE THREAD

**Issue by Taizunz** [dansza1/ptz-alv#10]
I woke up today to find the log looking like this:
![image](https://github.com/user-attachments/assets/0ddac9d4-7ba0-461e-a4cb-037e2e80db6a)

This does not happen after a restart of the app. In case it's an issue that's hard to track down, I will try and keep an eye on the log throughout today to see if I can spot when it happens.

**Comment by Taizunz** [comment]
I don't know what is causing it, but it did start happening again, this time with my own messages.
Over time it becomes worse and worse. This is over the span of just 10 minutes where it starts out normal and ends up spamming one message 6 times in a row.
![image](https://github.com/user-attachments/assets/13ea724e-21a2-4771-8d7f-80f6ee2a6395)

**Comment by Taizunz** [comment]
I spoke too soon, because I just found out what's causing it.
The bug is directly tied to Area Select being enabled/disabled repeatedly. The more you've enabled/disabled Area Select in your session, the more it's going to spam each command you send.

I tried by just enabling/disabling Area Select 10 times more, and it tried sending exactly 10 extra lines of my next click.

**Comment by dansza1** [comment]
Great bug finding and testing!

They were all related, the fix it did should resolve them all.
