### ISSUE TITLE
incorrect thumbnail for wolf center

### ISSUE THREAD

**Issue by bagel-deficient** [dansza1/ptz-alv#15]
The thumbnail for preset center shows the pond.  It does not look at the pond.

**Comment by bagel-deficient** [comment]
I will get a new thumbnail for it.  Is this a dumb thing to make an issue for? I don't know GitHub culture.

**Comment by wazix11** [comment]
Assuming I have time tomorrow I am planning to redo the wolfcorner presets and update the wolf and wolfin images

**Comment by bagel-deficient** [comment]
Oh yeah, I forgot you were redoing them.
