### ISSUE TITLE
Feature Request: Remember last visited admin page

### ISSUE THREAD

**Issue by Taizunz** [dansza1/ptz-alv#3]
The web app doesn't seem to remember the last Admin page you were on, so when you navigate between the Admin and Camera Control pages a lot, it always defaults to the top-most cameras settings on the Admin page.
It does remember the last Camera Control page you were on, so when you exit the Admin page it goes back to whatever camera control page you were last on, which is nice.

An alternative way of handling it (or perhaps an additional way via a user-configurable setting that can be added?) would be to load the Admin page that corresponds to the Camera Control page you came from when clicking the cogwheel, and vice versa. 
So if I'm on the wolf cam control page->Click the cogwheel->Wolf admin page loads. And if I then click the crows outdoor camera on the admin page->Click cogwheel->Crow outdoor cam control page loads. That way there's some semblance of continuity when navigating back and forth between Admin and Cam Control pages.

**Comment by dansza1** [comment]
Is it just the camera selection you want it to remember or also the menu you were on? Eg, if you were on "Twitch Settings" or "Interface Settings" do you want it to reopen to that or always default to opening with a camera selected (like it does now)?

**Comment by Taizunz** [comment]
Just the camera selection. Twitch Settings and Interface Settings don't get messed with nearly as much (if at all beyond the initial setup).

**Comment by dansza1** [comment]
ok, added so when you open the admin page it auto selects the camera which was selected on the main page.

**Comment by Taizunz** [comment]
You added this in 123b7b42d7aa69565a1c407ebae80b43962c4233

Thanks!
