### ISSUE TITLE
Feature Request: Display the broadcast latency

### ISSUE THREAD

**Issue by Taizunz** [dansza1/ptz-alv#5]
As a user of FFZ I absolutely love being able to quickly see what my current broadcast delay is when I'm watching a stream on Twitch, to quickly give me an indication of how far behind I am and whether or not I should do a player reset to fix my delay.
How it looks as an FFZ user: 
![image](https://github.com/user-attachments/assets/86051171-f944-44ab-9690-851e7d173967)

I'd love if this info could be added above the player somewhere.

**Comment by dansza1** [comment]
FFZ doesnt provide that information on an iframe.
